# Generated by Django 3.2.9 on 2021-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.TextField()),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
        ),
    ]
