# Generated by Django 3.2.9 on 2021-11-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='static/img/'),
        ),
    ]
